<?php

/**
 * @file
 * Contains rest_commerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_commerce module.
    case 'help.page.rest_commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("Define's a custom REST Resource") . '</p>';
      return $output;

    default:
  }
}
